# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a8bc8d6ad6469f9848d6b43c145ac40aeed794e772f736cc0cca0a2a9aa9278856ee9cdba038109bf11038301830f332c0338ebae3a0f69d78a4af0613cd92c

test:
  secret_key_base: 9a01a318854da42ae4bec6a40e605d0870255c29318a18d8c68be0f7d8512f81d5cd5a6ad026b9d48ebf7ff0fb1ef042277b5c01d6910bc29a5df8754fd78a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
